---
# tasks for serf
- user: name=serf

- group: name=serf

- get_url: url=https://dl.bintray.com/mitchellh/serf/{{ version }}_linux_amd64.zip
  args:
    dest: /tmp
    mode: 0644
    sha256sum: "{{ sha256sum }}"

- command: unzip -o /tmp/{{ version }}_linux_amd64.zip chdir=/usr/local/bin

- file: path=/usr/local/bin/serf owner=serf group=serf mode=0755 state=file

- file: path=/etc/serf.d owner=serf group=serf mode=0755 state=directory

- copy: src=./etc/init.d/serf dest=/etc/init.d/serf owner=serf group=serf mode=0755

- template: src=./etc/serf.conf dest=/etc/serf.conf owner=serf group=serf mode=0644

- file: path=/etc/consul.d mode=0755 state=directory
  when: consul_enabled

- copy: src=./etc/consul.d/serf.json dest=/etc/consul.d/serf.json owner=serf group=serf mode=0644
  when: consul_enabled

- service: name=serf state=started enabled=yes
